### ISSUE TITLE
The pickpocketed items are sometimes added to the inventory only after NPCs animation ends

### ISSUE THREAD

**Issue by SilvesTheRog** [fyryNy/ezPickPocket#1]
For example, pickpocketing dancers in Vlada's brothel in CoM: Archolos who are in the middle of a dance, will give the stolen items only when they stop dancing. The exp is awarded instantly.

https://youtu.be/d91nPLHz7FQ?t=8

Wonderful plugin btw, love it!

**Comment by fyryNy** [comment]
Items should be given automatically with no delay, in CoM prints for given items are added to ai queue of the npc that gives items (in this case npc from which you are stealing), so it's gonna show up only after their first task in queue is completed.
